---
- name: Network Getting Started First Playbook
  connection: network_cli
  become: yes
  hosts: all
  tasks: 
  
     - name: ensure that the desired
       cisco.ios.ios_command_module: 
         commands:
          - hostname test 
