---
    
- name: Cisco show version example
  connection: network_cli
  ansible_network_os: cisco.ios.ios
  hosts: all
  gather_facts: false
    
  tasks:
    - name: run show version on the routers
      ios_command:
        commands: show version | incl Version
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
