---
- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks: 
     - name: ensure that the desired
       cisco.ios.config: 
         commands:
          - hostname test 
