---
- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
   vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
  tasks:
    - name: Get config for IOS devices
      ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
        msg: "{{ hostvars[inventory_hostname]}}"
