---
- name: reboot network devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Backup current switch config (ios)
  cisco.ios.ios_config:
    backup: yes
  register: backup_ios_location
  when: ansible_network_os == 'cisco.ios.ios'
