---

- src: https://github.com/colin-mccarthy/ansible_cisco_ios_12.2_hardening_role.git
  name: ansible_cisco_ios_12.2_hardening_role
  scm: git
  version: master
  
- src: https://github.com/colin-mccarthy/ansible_cisco_ios_12.2_hardening_w-template.git
  name: ansible_cisco_ios_12.2_hardening_w-template
  scm: git
  version: master
  
- name: ansible-network.network-engine
  src: https://github.com/ansible-network/network-engine
  scm: git
  version: devel 

- name: backup_configs
  src: https://github.com/colin-mccarthy/backup_configs
  scm: git
  version: master

- name: servicenow_network_tickets
  src: https://github.com/colin-mccarthy/servicenow_network_tickets
  scm: git
  version: devel

